### ISSUE TITLE
twitter archive download comes as JSON and not CSV.

### ISSUE THREAD

**Issue by MubarakHAlketbi** [fellipec/YuriTweetDeleter#1]
i think the software requires an update for this?

**Comment by fellipec** [comment]
Twitter archive comes in a .zip file.
Inside the zip file you find the .CSV file. 
![Anotação 2019-04-25 223335](https://user-images.githubusercontent.com/16786721/56777915-2f77ea80-67aa-11e9-84e0-2915df94ff8b.jpg)

**Comment by davidmurr** [comment]
It appears that Twitter is no longer providing the CSV file in its archive (at least for some users?). I just downloaded my archive yesterday and the folder structure and files provided looks very different from the screenshot above. All of the data files are now JSON-formatted, as @MHketbi indicated.
![tweets js-screenshot](https://user-images.githubusercontent.com/640308/61731348-472f2280-ad49-11e9-8771-25c94cac6d50.png)
